AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-database

  Sample SAM Template for slack-database

Parameters:
  Bearer:
    Type: String
  SlackApi:
    Type: String

Resources:
  GetMessagesTaskSnsTopic:
    Type: AWS::SNS::Topic
  SendMessageTaskSnsTopic:
    Type: AWS::SNS::Topic
  ChannelDynamoDb:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  MessageDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: channel
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: channel
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
  GetTwitterListTweet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-twitter-list-tweet-lambda/
      Handler: get-twitter-list-tweet-lambda
      Runtime: go1.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          BEARER: !Ref Bearer
  ToSlackMessageLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: to-slack-message-lambda/
      Handler: to-slack-message-lambda
      Runtime: go1.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          SLACK_API: !Ref SlackApi
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref SendMessageTaskSnsTopic
  AddGetMessagesTaskStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state-machine/AddGetMessageTask.asl.yaml
      DefinitionSubstitutions:
        ChannelDynamoDbTable: !Ref ChannelDynamoDb
        GetMessagesTaskSnsTopicArn: !Ref GetMessagesTaskSnsTopic
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(15 minutes)"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ChannelDynamoDb
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt GetMessagesTaskSnsTopic.TopicName
  LaunchGetMessageStateMachineLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: launch-get-message-state-machine-lambda/
      Handler: launch-get-message-state-machine-lambda
      Runtime: go1.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          STEP_FUNCTION_ARN: !GetAtt GetMessageStateMachine.Arn
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref GetMessagesTaskSnsTopic
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt GetMessageStateMachine.Name
  GetMessageStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state-machine/GetMessage.asl.yaml
      DefinitionSubstitutions:
        SendMessageTaskSnsTopicArn: !Ref SendMessageTaskSnsTopic
        MessageDynamoDbTable: !Ref MessageDynamoDb
        ChannelDynamoDbTable: !Ref ChannelDynamoDb
        GetTwitterListTweetArn: !GetAtt GetTwitterListTweet.Arn
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref MessageDynamoDb
        - DynamoDBWritePolicy:
            TableName: !Ref ChannelDynamoDb
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SendMessageTaskSnsTopic.TopicName
        - LambdaInvokePolicy:
            FunctionName: !Ref GetTwitterListTweet
