AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-database

  Sample SAM Template for slack-database

Parameters:
  Bearer:
    Type: String

Resources:
  ToSlackMessageSqs:
    Type: AWS::SQS::Queue
  GetTwitterListTweet:
    Type: AWS::Serverless::Function
    Role: !GetAtt GetTwitterListTweetIamRole.Arn
    Properties:
      CodeUri: get-twitter-list-tweet-lambda/
      Handler: get-twitter-list-tweet-lambda
      Runtime: go1.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          BEARER: !Ref Bearer
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
  GetTwitterListTweetIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSStepFunctionsReadOnlyAccess
