AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  slack-database

  Sample SAM Template for slack-database

Parameters:
  Bearer:
    Type: String

Resources:
  ToSlackMessageSqs:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 60
      MessageRetentionPeriod: 86400
      FifoQueue: true
      ContentBasedDeduplication: true
  ChannelDynamoDb:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  MessageDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: channel
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: channel
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
  GetTwitterListTweet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get-twitter-list-tweet-lambda/
      Handler: get-twitter-list-tweet-lambda
      Runtime: go1.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          BEARER: !Ref Bearer
  ToSlackMessageLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: to-slack-message-lambda/
      Handler: to-slack-message-lambda
      Runtime: go1.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
  GetMessageStateFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state-machine/getMessage.asl.yaml
      DefinitionSubstitutions:
        ToSlackMessageSqsUrl: !Ref ToSlackMessageSqs
        DynamoDbPutItemArn: arn:aws:states:::dynamodb:putItem
        DynamoDbUpdateItemArn: arn:aws:states:::dynamodb:updateItem
        MessageDynamoDbTable: !Ref MessageDynamoDb
        ChannelDynamoDbTable: !Ref ChannelDynamoDb
        GetTwitterListTweetArn: !GetAtt GetTwitterListTweet.Arn
        ToSlackMessageSqsArn: arn:aws:states:::sqs:sendMessage
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref MessageDynamoDb
        - DynamoDBWritePolicy:
            TableName: !Ref ChannelDynamoDb
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ToSlackMessageSqs.QueueName
        - LambdaInvokePolicy:
            FunctionName: !Ref GetTwitterListTweet
